namespace ServerSideCharacter2
{
	public enum SSCMessageType
	{
		SyncPlayerHealth,
		SyncPlayerMana,
		SyncPlayerBank,
		RequestSaveData,
		RequestRegister,
		RequestSetGroup,
		RequestItem,
		RequestAuth,
		ResetPassword,
		LoginPassword,
		SendTimeSet,
		HelpCommand,
		KillCommand,
		ListCommand,
		SummonCommand,
		TPHereCommand,
		ButcherCommand,
		BanItemCommand,
		TPCommand,
		TimeCommand,
		ToggleExpert,
		ToggleHardMode,
		ToggleXmas,
		RegionCreateCommand,
		RegionRemoveCommand,
		RegionShareCommand,
		LockPlayer,
		TeleportPalyer,
		ToggleGodMode,
		SetGodMode,
		ServerSideCharacter,
		GenResources,
		ChestCommand,
		TPProtect,
		RSAPublic,
		SuccessLogin,
		FailLogin,
		WelcomeMessage,
		RequestOnlinePlayers,
		OnlinePlayersData,
		FriendRequest,
		GetFriends,
		FriendsData,
		ErrorMessage,
		InfoMessage
	}

	public enum GenerationType
	{
		Tree,
		Chest,
		Ore,
		Trap
	}
}
